language: node_js
node_js:
  - node

jobs:
  include:
    - stage: Coverage
      script: 
        - jest --coverage --reporters default jest-summarizing-reporter
        - coveralls < coverage/lcov.info
